// Product tutorials (panduan) for the SellOn blog. Same BlogPost shape as
// marketing posts, but with screenshots (section.image) and a real cover
// illustration (coverImage). Screenshots live under /public/tutorials/<slug>/.
//
// Generated by the marketing agent from the running app (real screenshots).
import type { BlogPost } from "./blog-posts";

export const tutorialPosts: BlogPost[] = [
  {
    slug: "mulai-cepat-setup-toko",
    category: "Panduan",
    title: "Mulai Cepat: Cara Membuat Toko di SellOn",
    excerpt:
      "Toko online-mu bisa live dalam 3 langkah dengan link sellon.id/nama-toko, siap diisi produk. Begini caranya dari awal.",
    publishedAt: "2026-05-29",
    readingTime: "4 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/mulai-cepat-setup-toko/cover.png",
    plan: "free",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: toko online-mu langsung live dengan link sellon.id/nama-toko, siap diisi produk.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Akun SellOn (login pakai Google). Setup ini gratis dan cuma 3 langkah.",
        },
      },
      {
        heading: "1. Isi identitas toko",
        paragraphs: [
          "Setelah login pertama kali, kamu langsung diarahkan ke halaman setup. Isi Nama Toko — ini yang dilihat pembeli. URL Toko terisi otomatis dari nama (boleh diubah sekarang, tapi tidak bisa diganti lagi setelah toko dibuat). Pilih Kategori Usaha, lalu klik Lanjut.",
        ],
        image: {
          src: "/tutorials/mulai-cepat-setup-toko/01-identitas-toko.png",
          alt: "Langkah 1 setup: isi nama toko, URL toko, dan kategori usaha",
          caption: "Langkah 1 — identitas toko.",
        },
      },
      {
        heading: "2. Tambah kontak & lokasi (opsional)",
        paragraphs: [
          "Isi Kota, Nomor WhatsApp, dan akun Instagram/TikTok kalau ada. Semua kolom di sini opsional — boleh dilewati dan diisi nanti dari Pengaturan. Klik Lanjut.",
        ],
        image: {
          src: "/tutorials/mulai-cepat-setup-toko/02-kontak-lokasi.png",
          alt: "Langkah 2 setup: isi kota, WhatsApp, dan sosial media toko",
          caption: "Langkah 2 — kontak & lokasi (boleh dilewati).",
        },
      },
      {
        heading: "3. Cek ringkasan, lalu buat toko",
        paragraphs: [
          "Halaman terakhir menampilkan ringkasan datamu dan apa yang akan terjadi. Kalau sudah pas, klik Buat Toko. Tokomu langsung live dan kamu masuk ke dasbor.",
        ],
        image: {
          src: "/tutorials/mulai-cepat-setup-toko/03-review-buat.png",
          alt: "Langkah 3 setup: review data lalu klik Buat Toko",
          caption: "Langkah 3 — review lalu Buat Toko.",
        },
      },
      {
        heading: "Tips",
        bullets: [
          "URL toko tidak bisa diganti setelah toko dibuat. Pikirkan baik-baik nama link-nya.",
          "Belum kepikiran kontak/sosial media? Lewati saja — semuanya bisa diedit di Pengaturan → Profil Toko.",
          "Setup pembayaran (Midtrans / transfer manual) tidak perlu sekarang; bisa diatur kapan saja sebelum jualan.",
        ],
      },
      {
        heading: "FAQ",
        paragraphs: [
          "Apakah langsung bisa terima pesanan? Toko sudah live, tapi sebaiknya tambah produk dulu dan atur pembayaran agar pembeli bisa checkout.",
          "Bisa ganti nama toko nanti? Nama toko bisa diubah; yang tidak bisa diubah adalah URL/link toko.",
        ],
      },
    ],
  },
  {
    slug: "kelola-produk",
    category: "Panduan",
    title: "Cara Mengelola Produk di SellOn",
    excerpt:
      "Dari menambah produk baru, mengatur harga dan stok, sampai varian dan opsi lanjutan — semua biar katalog tokomu rapi dan siap jualan.",
    publishedAt: "2026-05-29",
    readingTime: "5 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/kelola-produk/cover.png",
    plan: "free",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: katalog tokomu terisi rapi dan produk siap tampil di toko online maupun kasir.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Toko sudah dibuat, dan paket Gratis. Bagian lanjutan (Resep, Opsi, Penyajian) terhubung ke fitur Pro.",
        },
      },
      {
        heading: "1. Buka menu Produk, klik “Tambah Produk”",
        paragraphs: [
          "Dari menu kiri, klik Produk. Di sini semua barang tampil lengkap dengan harga, stok, dan status. Klik tombol hijau Tambah Produk di kanan atas.",
        ],
        image: {
          src: "/tutorials/kelola-produk/01-daftar-produk.png",
          alt: "Daftar produk dengan tombol Tambah Produk ditandai",
          caption: "Halaman Produk — daftar katalog + tombol Tambah Produk.",
        },
      },
      {
        heading: "2. Pilih tipe: Fisik atau Digital",
        paragraphs: [
          "Fisik untuk barang yang dikirim ke pembeli (makanan, kaos). Digital untuk file/akses lewat link (ebook, voucher) — otomatis terkirim setelah lunas, tanpa ongkir.",
        ],
      },
      {
        heading: "3. Isi info dan harga",
        paragraphs: [
          "Isi Nama Produk, Kategori, Harga, dan Stok. Kolom bertanda * wajib; sisanya bisa diedit nanti. Slug dibuat otomatis dari nama.",
          "Tiga kolom yang berguna: Alert Stok Rendah (badge “stok rendah” muncul saat stok menipis), Status (Aktif = langsung tampil di toko), dan Barcode/GTIN (biar produk bisa di-scan di kasir).",
        ],
        image: {
          src: "/tutorials/kelola-produk/02-form-info-harga.png",
          alt: "Formulir tambah produk terisi nama, kategori, dan harga",
          caption: "Formulir produk — informasi & harga.",
        },
      },
      {
        heading: "4. Tambah foto, varian, dan opsi lain",
        paragraphs: [
          "Scroll ke bawah untuk melengkapi foto, varian, dan bagian lain.",
        ],
        bullets: [
          "Foto — sampai 5 foto, langsung dari HP. Foto pertama jadi utama.",
          "Varian — aktifkan kalau ada pilihan dengan harga/stok sendiri (ukuran, warna).",
          "Potongan Volume — diskon otomatis saat beli minimal jumlah tertentu.",
        ],
        image: {
          src: "/tutorials/kelola-produk/03-resep-penyajian-opsi.png",
          alt: "Bagian foto, varian, opsi, dan penyajian pada formulir produk",
          caption: "Bagian lanjutan — foto, varian, opsi, penyajian.",
        },
      },
      {
        heading: "Bagian Pro yang terhubung",
        callout: {
          kind: "tip",
          title: "Butuh paket Pro",
          body: "Resep (bahan baku otomatis berkurang tiap terjual — butuh fitur Bahan Baku), Opsi (topping/ukuran yang menambah harga di kasir), dan Penyajian (Dine In/Take Away) aktif di paket Pro.",
        },
      },
      {
        heading: "5. Simpan",
        paragraphs: [
          "Klik Buat Produk. Produk langsung masuk katalog. Mau ubah nanti? Klik nama produk untuk edit, atau tombol ••• untuk duplikat/hapus.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Produk berfoto jauh lebih sering diklik daripada yang kosong.",
          "Pastikan harga sudah menutup modal + untung.",
          "Banyak produk? Pakai Upload Massal (XLSX) supaya tidak input satu-satu.",
        ],
      },
      {
        heading: "FAQ",
        paragraphs: [
          "Varian vs Opsi bedanya apa? Varian = pilihan dengan stok sendiri (S/M/L). Opsi = tambahan saat pesan yang menambah harga (extra shot, topping), dipakai di kasir.",
          "Kenapa Resep/Opsi belum bisa dipakai penuh? Bagian itu terhubung fitur Pro (Bahan Baku & Kasir POS). Toko Gratis akan melihat ajakan upgrade.",
        ],
      },
    ],
  },
  {
    slug: "resep-opsi-produk",
    category: "Panduan",
    title: "Cara Mengatur Resep & Opsi Produk di SellOn",
    excerpt:
      "Biar stok bahan berkurang otomatis tiap produk terjual dan pembeli bisa pilih ukuran/topping — atur Resep dan Opsi produk seperti ini.",
    publishedAt: "2026-05-29",
    readingTime: "5 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/resep-opsi-produk/cover.png",
    plan: "pro",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: tiap produk tahu bahan apa yang terpakai (stok bahan otomatis berkurang saat terjual) dan punya pilihan tambahan untuk pembeli seperti ukuran atau topping.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Paket Pro, dan bahan baku sudah didaftarkan (lihat panduan Bahan Baku & Stok).",
        },
      },
      {
        heading: "Resep Dasar Produk",
        paragraphs: [
          "Resep adalah daftar bahan yang otomatis terpakai tiap 1 produk terjual — baik di kasir maupun toko online. Gunanya: stok bahan berkurang sendiri, dan modal (HPP) produk terhitung otomatis.",
          "Dari Produk, klik produk yang mau diatur, scroll ke bagian Resep Dasar Produk, lalu klik Tambah Bahan untuk tiap bahan. Pilih bahan dari daftar dan isi jumlah yang terpakai per satu produk. Satuan (gram, pcs, ml) mengikuti pengaturan bahan tersebut.",
        ],
        image: {
          src: "/tutorials/resep-opsi-produk/01-resep-bahan.png",
          alt: "Resep produk dengan tiga bahan: Teh Hitam, Gula Pasir, dan Gelas Plastik",
          caption: "Contoh resep Es Teh Manis: 1 g teh, 15 g gula, 1 gelas plastik.",
        },
      },
      {
        heading: "Opsi Produk (Ukuran, Topping, dll)",
        paragraphs: [
          "Opsi adalah pilihan tambahan yang ditawarkan ke pembeli, dan tiap pilihan bisa menambah harga jual. Opsi muncul saat produk di-tap di Kasir POS.",
          "Di bagian Opsi Produk, klik Tambah Grup Opsi. Beri nama grup (misal “Ukuran”), pilih Pilih 1 atau pilih banyak, dan tandai Wajib kalau pembeli harus memilih. Lalu tambahkan tiap pilihan dengan nama dan tambahan harga, contoh: Reguler +Rp 0 dan Jumbo +Rp 3.000.",
        ],
        image: {
          src: "/tutorials/resep-opsi-produk/02-opsi-produk.png",
          alt: "Grup opsi Ukuran dengan pilihan Reguler dan Jumbo +Rp 3.000",
          caption: "Grup opsi “Ukuran” dengan dua pilihan harga.",
        },
      },
      {
        heading: "Penyajian (Dine In / Take Away)",
        paragraphs: [
          "Untuk warung makan/kafe, aktifkan Penyajian di formulir produk. Saat aktif, kasir diminta memilih Dine In atau Take Away ketika produk di-tap. Take Away bisa menambah biaya kemasan yang ditagih ke pembeli. Setelah semua diatur, klik Simpan Perubahan.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Resep bikin laporan modal akurat. Tanpa resep, produk tidak punya angka HPP — jadi laba tidak terhitung untuk produk itu.",
          "Opsi yang menambah bahan (extra shot, upsize) sebaiknya diisi resep opsi-nya juga, biar stok tetap akurat.",
          "Untuk produk dengan stok dan harga sendiri per pilihan (warna/ukuran baju), pakai Varian, bukan Opsi.",
        ],
      },
    ],
  },
  {
    slug: "bahan-baku-stok",
    category: "Panduan",
    title: "Cara Kelola Bahan Baku & Stok di SellOn",
    excerpt:
      "Catat bahan dan kemasan, pantau stok yang menipis, dan restock dengan modal terkini — supaya kamu tidak pernah kehabisan di tengah jualan.",
    publishedAt: "2026-05-29",
    readingTime: "5 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/bahan-baku-stok/cover.png",
    plan: "pro",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: kamu punya catatan stok bahan dan kemasan yang rapi, tahu mana yang menipis, dan bisa restock kapan saja. Ini juga jadi dasar perhitungan modal (HPP) otomatis lewat resep produk.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Paket Pro. Menu Bahan Baku ada di sidebar kiri.",
        },
      },
      {
        heading: "1. Buka menu Bahan Baku",
        paragraphs: [
          "Klik Bahan Baku di sidebar. Di atas ada tiga ringkasan penting: Nilai Stok (total nilai rupiah semua bahan), Jenis Bahan (jumlah bahan terdaftar), dan Stok Menipis (berapa bahan yang sudah di bawah ambang). Daftar di bawahnya menampilkan tiap bahan beserta stok, modal per satuan, dan tombol Restock.",
        ],
        image: {
          src: "/tutorials/bahan-baku-stok/01-daftar-bahan.png",
          alt: "Halaman Bahan Baku: ringkasan Nilai Stok, Jenis Bahan, Stok Menipis, dan daftar bahan dengan tombol Restock",
          caption: "Halaman Bahan Baku dengan ringkasan stok di atas.",
        },
      },
      {
        heading: "2. Tambah bahan baru",
        paragraphs: [
          "Klik Tambah Bahan. Isi nama (misal “Kopi Robusta”), pilih jenis (bahan atau kemasan/packaging), satuan dasar (gram, ml, pcs), modal per satuan, stok awal, dan ambang stok menipis. Ambang ini yang memunculkan badge “Menipis” supaya kamu ingat restock sebelum kehabisan.",
        ],
      },
      {
        heading: "3. Restock saat stok menipis",
        paragraphs: [
          "Klik Restock pada bahan yang mau ditambah. Isi jumlah yang masuk dan harga modal terkini (harga bahan bisa naik-turun, jadi modal selalu di-update ke harga terbaru). Tambahkan catatan kalau perlu, lalu klik Tambah Stok.",
        ],
        image: {
          src: "/tutorials/bahan-baku-stok/02-restock.png",
          alt: "Dialog Restock bahan: jumlah ditambah, harga modal terkini, dan catatan",
          caption: "Dialog Restock — tambah stok + perbarui modal.",
        },
      },
      {
        heading: "4. Pantau pergerakan stok",
        paragraphs: [
          "Tiap bahan punya riwayat pergerakan: restock, penyesuaian, dan pemakaian otomatis dari penjualan (lewat resep produk). Kamu juga bisa lakukan penyesuaian manual kalau ada selisih, atau pakai Stok Opname untuk hitung ulang fisik vs sistem.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Set ambang “stok menipis” realistis — cukup untuk waktu kamu belanja/produksi ulang.",
          "Pasang resep di produk (lihat panduan Resep & Opsi) supaya stok bahan berkurang otomatis tiap terjual.",
          "Bahan dan kemasan (gelas, box, stiker) sama-sama bisa dicatat di sini, jadi modal per produk lebih akurat.",
        ],
      },
    ],
  },
  {
    slug: "pembelian-supplier",
    category: "Panduan",
    title: "Cara Catat Pembelian (PO) & Supplier di SellOn",
    excerpt:
      "Catat pembelian bahan ke supplier lewat Purchase Order. Begitu barang diterima, stok bahan naik otomatis dan tercatat sebagai uang keluar.",
    publishedAt: "2026-05-29",
    readingTime: "5 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/pembelian-supplier/cover.png",
    plan: "pro",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: setiap pembelian bahan tercatat rapi per supplier. Saat barang sampai dan kamu tandai diterima, stok bahan bertambah otomatis dan modal diperbarui — jadi laporan arus kas dan HPP tetap akurat.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Paket Pro, dan bahan baku sudah didaftarkan. Menu Pembelian ada di sidebar kiri.",
        },
      },
      {
        heading: "1. Buka menu Pembelian",
        paragraphs: [
          "Klik Pembelian di sidebar. Daftar Purchase Order (PO) menampilkan tanggal, supplier, jumlah item, total, dan status. Status bergerak dari Draft → Dipesan → Diterima, dengan tombol aksi di kanan tiap baris.",
        ],
        image: {
          src: "/tutorials/pembelian-supplier/01-daftar-po.png",
          alt: "Daftar Purchase Order dengan status Draft, Dipesan, Diterima dan tombol Buat PO",
          caption: "Daftar PO — tiap baris punya status dan aksi lanjut.",
        },
      },
      {
        heading: "2. Buat PO baru",
        paragraphs: [
          "Klik Buat PO. Pilih Supplier (opsional), lalu tambahkan bahan yang dibeli: pilih bahan, isi jumlah, dan modal per satuan. Klik Tambah Bahan untuk menambah baris. Total dihitung otomatis. Klik Simpan PO.",
        ],
        image: {
          src: "/tutorials/pembelian-supplier/02-buat-po.png",
          alt: "Formulir Purchase Order baru: pilih supplier, bahan Kopi Robusta, jumlah, dan modal",
          caption: "Buat PO — pilih supplier dan daftar bahan yang dibeli.",
        },
      },
      {
        heading: "3. Tandai diterima saat barang sampai",
        paragraphs: [
          "Setelah PO dibuat (Draft), tandai Dipesan saat kamu benar-benar memesan ke supplier. Ketika barang sampai, klik Terima. Saat itu juga: stok bahan otomatis bertambah sesuai jumlah PO, modal bahan diperbarui ke harga pembelian terbaru, dan nilainya tercatat sebagai uang keluar di Analytics.",
        ],
      },
      {
        heading: "Tentang supplier",
        paragraphs: [
          "Supplier dipilih langsung di dalam alur PO, dan daftar supplier-mu bisa dikelola dari menu terkait. Mengisi supplier membantu kamu melihat riwayat pembelian per supplier dan membandingkan harga.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Selalu klik Terima saat barang sampai — kalau tidak, stok bahan tidak akan bertambah.",
          "Update modal per satuan tiap PO supaya HPP produk mengikuti harga bahan terkini.",
          "PO yang masih Draft belum memengaruhi stok maupun arus kas; aman untuk menyiapkan dulu.",
        ],
      },
    ],
  },
  {
    slug: "stok-opname",
    category: "Panduan",
    title: "Cara Stok Opname (Hitung Fisik) Bahan di SellOn",
    excerpt:
      "Hitung stok fisik bahan dan bandingkan dengan catatan sistem. Selisihnya otomatis jadi penyesuaian stok — biar angka di sistem selalu cocok dengan kenyataan.",
    publishedAt: "2026-05-29",
    readingTime: "4 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/stok-opname/cover.png",
    plan: "pro",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: catatan stok bahan di sistem cocok dengan stok fisik di gudang/dapur. Selisih (susut, salah catat, sisa) otomatis jadi penyesuaian.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Paket Pro. Menu Stok Opname bisa dibuka dari halaman Bahan Baku atau lewat sidebar.",
        },
      },
      {
        heading: "1. Mulai opname",
        paragraphs: [
          "Buka Stok Opname. Kamu akan lihat riwayat opname sebelumnya (Draft atau sudah Diposting). Klik Mulai Opname untuk membuat hitungan baru.",
        ],
        image: {
          src: "/tutorials/stok-opname/01-riwayat-opname.png",
          alt: "Halaman Stok Opname dengan riwayat opname dan tombol Mulai Opname",
          caption: "Riwayat opname + tombol Mulai Opname.",
        },
      },
      {
        heading: "2. Isi hasil hitung fisik",
        paragraphs: [
          "Sistem menampilkan semua bahan beserta stok menurut catatan (kolom Sistem). Isi kolom Hitung Fisik dengan hasil hitunganmu di lapangan. Selisih dihitung otomatis: merah kalau fisik lebih sedikit dari sistem, hijau kalau lebih banyak.",
        ],
        image: {
          src: "/tutorials/stok-opname/02-hitung-fisik.png",
          alt: "Tabel hitung fisik: kolom Sistem, Hitung Fisik, dan Selisih dengan contoh -5 dan +3",
          caption: "Isi hitung fisik; selisih dihitung otomatis.",
        },
      },
      {
        heading: "3. Posting opname",
        paragraphs: [
          "Setelah semua diisi, klik Posting Opname. Stok bahan langsung disesuaikan ke angka fisik, dan penyesuaian tercatat di riwayat pergerakan tiap bahan. Kalau belum yakin, simpan dulu sebagai Draft dan lanjutkan nanti.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Lakukan opname rutin (mingguan/bulanan) supaya selisih kecil dan mudah ditelusuri.",
          "Bahan yang tidak kamu ubah angkanya dianggap sudah cocok (selisih 0).",
          "Opname bagus dilakukan saat toko tutup, supaya stok tidak berubah saat dihitung.",
        ],
      },
    ],
  },
  {
    slug: "storefront-online",
    category: "Panduan",
    title: "Cara Atur Storefront (Toko Online) di SellOn",
    excerpt:
      "Atur tampilan toko online-mu — logo, banner, warna tema, dan layout produk — lalu bagikan satu link supaya pembeli bisa lihat katalog dan checkout sendiri.",
    publishedAt: "2026-05-29",
    readingTime: "5 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/storefront-online/cover.png",
    plan: "free",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: toko online-mu tampil rapi dan profesional di link sellon.id/nama-toko. Pembeli bisa lihat katalog, buka detail produk, dan checkout sendiri tanpa kamu balas chat satu per satu.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Toko sudah dibuat dan minimal ada beberapa produk aktif. Pengaturan tampilan ada di Pengaturan → Storefront.",
        },
      },
      {
        heading: "1. Atur tampilan toko",
        paragraphs: [
          "Buka Pengaturan → Storefront. Di sini kamu bisa upload Logo Toko (kotak ~512×512, tampil sebagai avatar) dan Banner Toko (landscape ~1600×500). Pilih Warna Tema yang dipakai untuk tombol, badge, dan aksen di halaman publik. Lalu pilih Layout Produk: Grid (kartu besar multi-kolom), Daftar (thumbnail kecil + info), atau Sorotan (produk pertama tampil besar — cocok untuk fashion/hero product). Klik Preview untuk lihat live, lalu Terapkan.",
        ],
        image: {
          src: "/tutorials/storefront-online/01-tampilan-toko.png",
          alt: "Pengaturan Storefront: pilihan Warna Tema dan Layout Produk (Grid/Daftar/Sorotan)",
          caption: "Pengaturan Storefront — warna tema & layout produk.",
        },
        callout: {
          kind: "tip",
          title: "Warna tema & layout = fitur Pro",
          body: "Ganti warna tema dan pilih layout produk tersedia di paket Pro. Logo, banner, dan link toko bisa dipakai semua paket.",
        },
      },
      {
        heading: "2. Lihat halaman toko publik",
        paragraphs: [
          "Klik Lihat halaman toko (atau buka langsung sellon.id/nama-toko). Inilah yang dilihat pembeli: header toko, kategori, Produk Unggulan, dan daftar produk lengkap dengan harga dan kolom pencarian.",
        ],
        image: {
          src: "/tutorials/storefront-online/02-etalase-publik.png",
          alt: "Etalase publik Toko Ijo: kategori, Produk Unggulan, dan grid produk dengan harga",
          caption: "Tampilan toko yang dilihat pembeli.",
        },
      },
      {
        heading: "3. Alur beli pembeli",
        paragraphs: [
          "Pembeli klik sebuah produk untuk membuka halaman detail: foto, deskripsi, pilihan varian, jumlah, dan subtotal. Dari sini mereka bisa Tambah ke Keranjang atau Beli Sekarang, lalu lanjut ke checkout (isi identitas → pengiriman → pembayaran). Ongkir dihitung otomatis di checkout.",
        ],
        image: {
          src: "/tutorials/storefront-online/03-detail-produk.png",
          alt: "Halaman detail produk: pilih varian, jumlah, subtotal, tombol Beli Sekarang dan Tambah ke Keranjang",
          caption: "Halaman detail produk dari sisi pembeli.",
        },
      },
      {
        heading: "Tips",
        bullets: [
          "Pasang logo dan banner — toko dengan identitas visual terlihat lebih dipercaya.",
          "Tandai produk andalan sebagai “unggulan” supaya muncul di bagian atas etalase.",
          "Bagikan link toko di bio WhatsApp, status, dan setiap broadcast.",
        ],
      },
    ],
  },
  {
    slug: "pesanan",
    category: "Panduan",
    title: "Cara Kelola Pesanan di SellOn",
    excerpt:
      "Semua pesanan dari toko online masuk ke satu halaman. Konfirmasi, verifikasi pembayaran, kirim update via WhatsApp, sampai tandai selesai — tanpa ada yang terlewat.",
    publishedAt: "2026-05-29",
    readingTime: "5 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/pesanan/cover.png",
    plan: "free",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: kamu punya satu tempat untuk memantau semua pesanan, tahu mana yang perlu dikonfirmasi atau dikirim, dan bisa kirim update ke pembeli lewat WhatsApp dalam sekali klik.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Toko aktif dengan pesanan masuk. Menu Pesanan ada di sidebar.",
        },
      },
      {
        heading: "1. Pantau daftar pesanan",
        paragraphs: [
          "Buka Pesanan. Daftar menampilkan nomor order, pembeli, total, status, dan status pembayaran. Pakai Filter untuk menyaring berdasarkan status (Menunggu, Dikonfirmasi, Diproses, Dikirim, Selesai) atau pembayaran (Belum bayar, Bukti dikirim, Lunas). Butuh rekap? Klik Export CSV.",
        ],
        image: {
          src: "/tutorials/pesanan/01-daftar-pesanan.png",
          alt: "Daftar pesanan dengan filter status, status pembayaran, dan tombol Export CSV",
          caption: "Daftar pesanan dengan filter dan export.",
        },
      },
      {
        heading: "2. Kelola satu pesanan",
        paragraphs: [
          "Klik Lihat detail. Di halaman detail kamu bisa menggerakkan status pesanan (Konfirmasi → Proses → Kirim → Selesai), melihat produk yang dipesan, dan menangani pembayaran: Konfirmasi Pembayaran Manual (kalau pembeli sudah transfer), Generate Link Midtrans, atau verifikasi bukti transfer. Panel Riwayat Status menunjukkan progres pesanan.",
        ],
        image: {
          src: "/tutorials/pesanan/02-detail-pesanan.png",
          alt: "Detail pesanan: tombol Konfirmasi Pesanan, opsi pembayaran, riwayat status, dan kirim WhatsApp",
          caption: "Detail pesanan — status, pembayaran, dan kirim WA.",
        },
      },
      {
        heading: "3. Kirim update via WhatsApp",
        paragraphs: [
          "Di panel Kirim WhatsApp, kamu bisa kirim Konfirmasi Pesanan, Link Pembayaran, atau Update Resi ke nomor pembeli. Pesan otomatis terisi dari template (bisa kamu ubah di Pengaturan → WhatsApp), jadi tinggal klik dan kirim.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Konfirmasi pesanan baru secepatnya supaya pembeli tenang dan tidak batal.",
          "Untuk transfer manual, cek mutasi rekening dulu sebelum Konfirmasi Pembayaran Manual / Tandai Lunas.",
          "Pakai Export CSV untuk rekap penjualan ke pembukuan atau Excel.",
        ],
      },
    ],
  },
  {
    slug: "kasir-pos",
    category: "Panduan",
    title: "Cara Pakai Kasir POS di SellOn",
    excerpt:
      "Layani penjualan langsung di toko: buka shift, tap produk, pilih varian dan opsi, terima pembayaran tunai/QRIS/split, lalu tutup shift dengan rekap kas yang rapi.",
    publishedAt: "2026-05-29",
    readingTime: "6 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/kasir-pos/cover.png",
    plan: "pro",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: kamu bisa melayani transaksi tatap muka dengan cepat, stok berkurang otomatis, dan uang kas terhitung rapi tiap shift.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Paket Pro. Buka menu Buka Kasir di sidebar. Untuk scan barcode, hubungkan scanner atau ketik di kolom cari.",
        },
      },
      {
        heading: "1. Buka shift kasir",
        paragraphs: [
          "Mulai dengan membuka shift dan mengisi kas awal (modal di laci). Layar kasir menampilkan grid produk di kiri dan keranjang Transaksi di kanan. Tombol Hold, Kas (kas masuk/keluar), dan Tutup Shift ada di atas.",
        ],
        image: {
          src: "/tutorials/kasir-pos/01-layar-kasir.png",
          alt: "Layar Kasir POS: grid produk, kolom cari/scan barcode, dan panel transaksi di kanan",
          caption: "Layar kasir — grid produk + keranjang transaksi.",
        },
      },
      {
        heading: "2. Tambah produk ke transaksi",
        paragraphs: [
          "Cari atau scan produk (nama / barcode / GTIN), lalu tap. Kalau produk punya varian atau opsi, muncul picker untuk memilih ukuran, topping, atau Dine In/Take Away. Pilih, lalu tambahkan ke keranjang.",
        ],
        image: {
          src: "/tutorials/kasir-pos/02-pilih-varian.png",
          alt: "Picker varian produk di POS: memilih ukuran dan tingkat gula sebelum masuk keranjang",
          caption: "Tap produk bervarian → pilih varian/opsi dulu.",
        },
      },
      {
        heading: "3. Diskon, poin, dan pelanggan",
        paragraphs: [
          "Di panel transaksi kamu bisa menerapkan diskon, memilih pelanggan (atau scan kartu member untuk diskon member + bonus poin otomatis), dan redeem poin loyalty. Diskon volume berjalan otomatis kalau jumlah memenuhi syarat.",
        ],
      },
      {
        heading: "4. Bayar (termasuk split payment)",
        paragraphs: [
          "Klik Bayar. Pilih satu metode (Tunai, QRIS, Transfer, Midtrans, EDC) atau pakai Split untuk membagi ke beberapa metode. Untuk tunai, isi Uang Diterima — kembalian dihitung otomatis. Klik Proses Pembayaran, lalu struk bisa dicetak (browser/thermal) atau dikirim via WhatsApp.",
        ],
        image: {
          src: "/tutorials/kasir-pos/03-pembayaran.png",
          alt: "Layar pembayaran POS: pilih metode Tunai/QRIS/Transfer/EDC atau Split, isi uang diterima, kembalian otomatis",
          caption: "Pembayaran — satu metode atau split, kembalian otomatis.",
        },
      },
      {
        heading: "5. Tutup shift",
        paragraphs: [
          "Di akhir, klik Tutup Shift dan masukkan kas akhir (uang fisik di laci). Sistem membandingkan dengan yang seharusnya, jadi selisih kas langsung ketahuan. Rekap tiap shift bisa dilihat di Riwayat Shift, dan ringkasan penjualan kasir di Laporan POS.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Selalu isi kas awal dengan benar supaya rekap akhir shift akurat.",
          "Pakai kolom cari (F2) untuk scan barcode cepat saat antrean ramai.",
          "Catat pengeluaran laci (beli galon, parkir) lewat tombol Kas supaya pembukuan cocok.",
        ],
      },
    ],
  },
  {
    slug: "loyalty-poin",
    category: "Panduan",
    title: "Cara Atur Loyalty Poin di SellOn",
    excerpt:
      "Kasih poin tiap pelanggan belanja, dan biarkan mereka tukar poin jadi diskon. Cara sederhana bikin pembeli balik lagi.",
    publishedAt: "2026-05-29",
    readingTime: "4 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/loyalty-poin/cover.png",
    plan: "pro",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: tiap pembelian otomatis memberi poin ke pelanggan, dan poin itu bisa ditukar jadi diskon di kasir — dorongan halus supaya mereka belanja lagi.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Paket Pro. Buka Pengaturan → Loyalty.",
        },
      },
      {
        heading: "1. Aktifkan dan atur rate poin",
        paragraphs: [
          "Nyalakan Aktifkan Loyalty Point. Lalu atur dua angka: Earn Rate (berapa rupiah belanja untuk dapat 1 poin) dan Redeem Rate (nilai 1 poin saat ditukar jadi diskon). Contoh: belanja Rp 1.000 = 1 poin, dan 1 poin = Rp 100 diskon — artinya cashback efektif sekitar 10%. Klik Simpan Pengaturan.",
        ],
        image: {
          src: "/tutorials/loyalty-poin/01-pengaturan-loyalty.png",
          alt: "Pengaturan Loyalty: toggle aktif, Earn Rate, dan Redeem Rate dengan contoh perhitungan",
          caption: "Pengaturan Loyalty — atur earn & redeem rate.",
        },
      },
      {
        heading: "2. Poin terkumpul otomatis",
        paragraphs: [
          "Setelah aktif, setiap transaksi yang terhubung ke pelanggan akan menambah poin sesuai earn rate. Saldo poin pelanggan bisa dilihat di halaman detail pelanggan.",
        ],
      },
      {
        heading: "3. Pakai poin di kasir",
        paragraphs: [
          "Di Kasir POS, pilih pelanggan (atau scan kartu member), lalu gunakan opsi redeem poin untuk memotong total belanja sesuai redeem rate. Sisa poin otomatis terupdate.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Pastikan redeem rate lebih kecil dari earn rate supaya program tidak bikin rugi.",
          "Hubungkan setiap transaksi ke pelanggan supaya poin benar-benar terkumpul.",
          "Gabungkan dengan Membership supaya pelanggan setia dapat bonus poin lebih besar.",
        ],
      },
    ],
  },
  {
    slug: "membership",
    category: "Panduan",
    title: "Cara Atur Membership (Tier Pelanggan) di SellOn",
    excerpt:
      "Naikkan pelanggan ke tier seperti Perak, Emas, Platinum berdasarkan total belanja. Tiap tier bisa kasih bonus poin dan diskon member otomatis di kasir.",
    publishedAt: "2026-05-29",
    readingTime: "4 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/membership/cover.png",
    plan: "pro",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: pelanggan otomatis naik tier sesuai total belanja, dan setiap tier memberi bonus poin (multiplier) plus diskon member yang langsung dipakai di kasir.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Paket Pro. Buka Pengaturan → Membership. Pasangkan dengan Loyalty Poin untuk hasil maksimal.",
        },
      },
      {
        heading: "1. Buat tier membership",
        paragraphs: [
          "Klik Tambah Tier dan isi tiap baris: Nama Tier (misal Perak/Emas/Platinum), Min. Belanja (total belanja minimum untuk masuk tier itu), Bonus Poin (×) (pengali poin loyalty), dan Diskon (%) (potongan otomatis untuk member tier itu). Aktifkan tiap tier, lalu klik Simpan Tier.",
        ],
        image: {
          src: "/tutorials/membership/01-pengaturan-membership.png",
          alt: "Tabel tier membership: Perak, Emas, Platinum dengan min belanja, bonus poin, dan diskon",
          caption: "Tier membership otomatis dari total belanja.",
        },
      },
      {
        heading: "2. Tier naik otomatis",
        paragraphs: [
          "Pelanggan otomatis dievaluasi berdasarkan total belanjanya. Badge tier muncul di halaman pelanggan, jadi kamu tahu siapa pelanggan VIP-mu.",
        ],
      },
      {
        heading: "3. Kartu member QR + scan di kasir",
        paragraphs: [
          "Dari halaman detail pelanggan, kamu bisa buat dan cetak Kartu Member ber-QR. Saat pelanggan datang, scan kode kartunya di pemilih pelanggan di Kasir POS — diskon member dan bonus poin tier-nya langsung diterapkan ke transaksi.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Buat selisih manfaat antar tier yang terasa, supaya pelanggan termotivasi naik tier.",
          "Diskon member + bonus poin sebaiknya tetap menyisakan margin sehat.",
          "Promosikan program member di struk dan storefront supaya makin banyak yang daftar.",
        ],
      },
    ],
  },
  {
    slug: "promo-diskon",
    category: "Panduan",
    title: "Cara Buat Promo & Diskon di SellOn",
    excerpt:
      "Bikin kode promo (misal HEMAT10) untuk checkout, atur diskon persentase atau nominal, dan kasih potongan otomatis untuk pembelian dalam jumlah banyak.",
    publishedAt: "2026-05-29",
    readingTime: "4 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/promo-diskon/cover.png",
    plan: "free",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: kamu punya kode promo yang bisa dipakai pembeli saat checkout, plus diskon otomatis untuk pembelian banyak — alat sederhana untuk dorong penjualan.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Toko aktif. Menu Promo ada di sidebar.",
        },
      },
      {
        heading: "1. Buat kode promo",
        paragraphs: [
          "Buka Promo, klik Buat Promo. Isi Kode Promo (otomatis di-uppercase, hindari spasi — misal HEMAT10), pilih Tipe Diskon (Persentase, Nominal Rp, atau Gratis Ongkir), lalu isi nilainya. Atur Minimum Belanja, Kuota Pemakaian (0 = tanpa batas), dan masa berlaku (Mulai Berlaku & Kadaluarsa). Aktifkan, lalu klik Buat Promo.",
        ],
        image: {
          src: "/tutorials/promo-diskon/01-buat-promo.png",
          alt: "Formulir Buat Promo: kode HEMAT10, tipe diskon persentase, minimum belanja, dan kuota",
          caption: "Buat kode promo untuk checkout.",
        },
      },
      {
        heading: "2. Pembeli pakai kode saat checkout",
        paragraphs: [
          "Pembeli memasukkan kode promo di halaman checkout toko online. Kalau syarat (minimum belanja, masa berlaku, sisa kuota) terpenuhi, diskon langsung terpotong dari total.",
        ],
      },
      {
        heading: "3. Diskon volume (beli banyak lebih murah)",
        paragraphs: [
          "Selain kode promo, kamu bisa atur Potongan Volume langsung di formulir produk: beri diskon otomatis saat pembeli beli minimal jumlah tertentu (misal beli 12 dapat potongan). Diskon volume ini juga berjalan otomatis di Kasir POS tanpa perlu kode.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Pakai kode yang mudah diingat dan relevan dengan kampanye (LEBARAN, GAJIAN).",
          "Set kuota dan masa berlaku supaya promo tidak kebablasan dan bikin rugi.",
          "Pakai diskon volume untuk produk yang untung kalau dibeli banyak (grosir, paket).",
        ],
      },
    ],
  },
  {
    slug: "pelanggan",
    category: "Panduan",
    title: "Cara Kelola Pelanggan di SellOn",
    excerpt:
      "Semua pembeli tercatat otomatis dengan segmen, total belanja, dan riwayat order. Hubungi via WhatsApp, lihat poin, dan cetak kartu member dari satu tempat.",
    publishedAt: "2026-05-29",
    readingTime: "4 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/pelanggan/cover.png",
    plan: "free",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: kamu kenal pelanggan-mu — siapa yang paling sering belanja, siapa yang lama tidak order — dan bisa menghubungi mereka langsung lewat WhatsApp.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Toko aktif dengan pesanan masuk. Menu Pelanggan ada di sidebar. Data pelanggan tercatat otomatis dari pesanan.",
        },
      },
      {
        heading: "1. Lihat daftar & segmen pelanggan",
        paragraphs: [
          "Buka Pelanggan. Tiap pembeli otomatis masuk dengan Segmen (Baru, Reguler, Loyal, VIP, Blacklist), jumlah order, total belanja, dan tanggal order terakhir. Saring lewat tab segmen, atau klik Hubungi via WhatsApp untuk chat langsung. Butuh data mentah? Export CSV.",
        ],
        image: {
          src: "/tutorials/pelanggan/01-daftar-pelanggan.png",
          alt: "Daftar pelanggan dengan segmen, total belanja, dan tombol Hubungi via WhatsApp",
          caption: "Daftar pelanggan dengan segmen otomatis.",
        },
      },
      {
        heading: "2. Buka detail pelanggan",
        paragraphs: [
          "Klik Lihat detail. Halaman detail menampilkan segmen, badge tier membership, lifetime stats (jumlah order, total belanja, order terakhir), saldo poin loyalty, dan riwayat pesanan. Dari sini kamu juga bisa membuat dan mencetak Kartu Member ber-QR untuk discan di kasir.",
        ],
        image: {
          src: "/tutorials/pelanggan/02-detail-pelanggan.png",
          alt: "Detail pelanggan: segmen Loyal, tier Platinum, lifetime stats, saldo poin, dan riwayat pesanan",
          caption: "Detail pelanggan — profil lengkap + kartu member.",
        },
      },
      {
        heading: "Tips",
        bullets: [
          "Hubungi pelanggan Loyal/VIP dengan penawaran khusus — mereka penyumbang omzet terbesar.",
          "Pelanggan yang lama tidak order bisa di-follow up lewat WhatsApp dengan promo.",
          "Cetak kartu member untuk pelanggan setia supaya transaksi di kasir makin cepat.",
        ],
      },
    ],
  },
  {
    slug: "laporan",
    category: "Panduan",
    title: "Cara Baca Laporan Penjualan di SellOn",
    excerpt:
      "Lihat omzet, jumlah order, rata-rata transaksi, produk terlaris, sampai laporan konsumsi bahan — biar keputusan jualanmu berdasar data, bukan feeling.",
    publishedAt: "2026-05-29",
    readingTime: "4 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/laporan/cover.png",
    plan: "pro",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: kamu tahu performa toko dalam sekejap — berapa omzet, order, produk apa yang laku, dan berapa bahan yang terpakai.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Laporan tersedia di paket Pro. Menu Laporan ada di sidebar.",
        },
      },
      {
        heading: "1. Overview penjualan",
        paragraphs: [
          "Buka Laporan. Di atas ada KPI: Revenue, Order Berbayar, Total Order, dan Avg. Order Value. Pilih rentang Harian/Mingguan/Bulanan. Grafik Revenue menunjukkan tren penjualan, dan di bawahnya ada daftar produk terlaris (serta pelanggan top). Butuh data mentah? Download Laporan.",
        ],
        image: {
          src: "/tutorials/laporan/01-laporan-overview.png",
          alt: "Laporan overview: KPI revenue, order, AOV, grafik revenue harian, dan produk terlaris",
          caption: "Overview penjualan — KPI, grafik, dan produk terlaris.",
        },
      },
      {
        heading: "2. Laporan konsumsi bahan",
        paragraphs: [
          "Buka tab Laporan Bahan. Di sini terlihat berapa banyak tiap bahan terpakai dalam periode tertentu, total biayanya, dan kontribusi tiap bahan. Data ini muncul otomatis dari penjualan produk ber-resep — berguna untuk kontrol modal dan rencana belanja bahan.",
        ],
        image: {
          src: "/tutorials/laporan/02-laporan-bahan.png",
          alt: "Laporan Konsumsi Bahan: total biaya bahan, bahan terpakai, dan tabel konsumsi per bahan",
          caption: "Laporan konsumsi bahan dari produk ber-resep.",
        },
      },
      {
        heading: "Tips",
        bullets: [
          "Pantau produk terlaris untuk menentukan stok dan promo.",
          "Bandingkan periode (mingguan/bulanan) untuk lihat tren naik atau turun.",
          "Laporan konsumsi bahan cuma akurat kalau produk sudah dipasang resep.",
        ],
      },
    ],
  },
  {
    slug: "analytics-360",
    category: "Panduan",
    title: "Cara Pakai Analytics 360 di SellOn",
    excerpt:
      "Pantau arus kas masuk-keluar, laba kotor dan margin, serta tren penjualan dalam satu dashboard. Plus catatan kas manual untuk pemasukan/pengeluaran di luar transaksi.",
    publishedAt: "2026-05-29",
    readingTime: "4 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/analytics-360/cover.png",
    plan: "pro",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: kamu paham kesehatan finansial toko — bukan cuma omzet, tapi juga laba dan arus kas — supaya bisa ambil keputusan dengan tenang.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Paket Pro. Menu Analytics ada di sidebar. Pasang resep produk agar angka laba/HPP akurat.",
        },
      },
      {
        heading: "1. Baca KPI utama",
        paragraphs: [
          "Buka Analytics. Empat angka kunci: Pendapatan (omzet), Laba Kotor + margin %, Arus Kas Bersih (masuk dikurangi keluar), dan Order + AOV. Laba dihitung dari konsumsi bahan (resep) dan biaya dropship — produk tanpa resep belum punya angka HPP, jadi pasang resep biar akurat.",
        ],
        image: {
          src: "/tutorials/analytics-360/01-analytics-kpi.png",
          alt: "Analytics 360: KPI Pendapatan, Laba Kotor dengan margin, Arus Kas Bersih, Order, dan grafik tren pendapatan",
          caption: "KPI utama — pendapatan, laba, arus kas.",
        },
      },
      {
        heading: "2. Lihat tren & arus kas",
        paragraphs: [
          "Di bawah KPI ada grafik Tren Pendapatan, Arus Kas (Masuk vs Keluar), dan komposisi Metode Pembayaran. Atur rentang tanggal di atas untuk fokus ke periode tertentu.",
        ],
        image: {
          src: "/tutorials/analytics-360/02-analytics-chart.png",
          alt: "Grafik analytics: tren pendapatan dan arus kas masuk vs keluar",
          caption: "Grafik tren pendapatan & arus kas.",
        },
      },
      {
        heading: "3. Catatan kas manual",
        paragraphs: [
          "Ada pemasukan atau pengeluaran di luar transaksi toko (sewa, gaji, modal masuk)? Catat lewat Catatan Kas Manual supaya arus kas bersih mencerminkan kondisi sebenarnya.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Margin tinggi tidak selalu akurat kalau banyak produk belum punya resep — lengkapi resepnya.",
          "Catat pengeluaran rutin (sewa, listrik) di catatan kas manual untuk gambaran kas yang jujur.",
          "Pantau arus kas, bukan cuma omzet — bisnis sehat itu yang kasnya positif.",
        ],
      },
    ],
  },
  {
    slug: "dine-in-qr-meja",
    category: "Panduan",
    title: "Cara Aktifkan QR Meja & Self-Order (Dine-In) di SellOn",
    excerpt:
      "Pasang QR di tiap meja, biarkan pelanggan pesan sendiri dari HP, dan pesanan langsung masuk ke kasir. Cocok untuk kafe dan warung makan.",
    publishedAt: "2026-05-29",
    readingTime: "5 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/dine-in-qr-meja/cover.png",
    plan: "pro",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: tiap meja punya QR sendiri. Pelanggan scan, pilih menu, dan pesanan masuk ke sistem dengan nomor antrian — tanpa kamu harus mencatat manual.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Paket Pro. Pengaturan ada di Pengaturan → Meja & QR.",
        },
      },
      {
        heading: "1. Aktifkan dine-in & buat meja",
        paragraphs: [
          "Buka Pengaturan → Meja & QR. Nyalakan Pesan via QR Meja (Dine-In). Atur juga apakah pembayaran di kasir atau (opsional) bayar online dulu, dan apakah Kitchen Display dipakai. Lalu klik Tambah Meja untuk tiap meja (beri label dan area Dalam/Luar). Tiap meja punya tombol Cetak untuk mencetak QR-nya.",
        ],
        image: {
          src: "/tutorials/dine-in-qr-meja/01-meja-qr.png",
          alt: "Pengaturan Meja & QR: toggle dine-in, mode bayar, dan daftar meja dengan tombol Cetak QR",
          caption: "Aktifkan dine-in dan buat meja + QR.",
        },
      },
      {
        heading: "2. Pelanggan scan QR & pilih cara makan",
        paragraphs: [
          "Saat pelanggan scan QR di meja, mereka masuk ke halaman self-order. Pertama mereka pilih Makan di Tempat atau Bawa Pulang.",
        ],
        image: {
          src: "/tutorials/dine-in-qr-meja/02-self-order.png",
          alt: "Halaman self-order pelanggan: pilih Makan di Tempat atau Bawa Pulang",
          caption: "Pelanggan pilih cara makan dari HP.",
        },
      },
      {
        heading: "3. Pilih menu & kirim pesanan",
        paragraphs: [
          "Pelanggan memilih produk dari menu, mengisi nama dan nomor WhatsApp, lalu mengirim pesanan dan mendapat nomor antrian. Pesanannya langsung masuk ke sistem (dan ke Kitchen Display kalau aktif).",
        ],
        image: {
          src: "/tutorials/dine-in-qr-meja/03-self-order-menu.png",
          alt: "Menu self-order: daftar produk dengan tombol Pilih",
          caption: "Menu self-order dari sisi pelanggan.",
        },
      },
      {
        heading: "Batasan saat ini",
        callout: {
          kind: "warn",
          title: "Yang belum didukung di self-order",
          body: "Versi awal self-order via QR meja fokus ke produk tanpa varian dan pembayaran di kasir. Pemilihan varian/opsi dan bayar online-dulu untuk dine-in belum aktif. Pembayaran dine-in diselesaikan lewat Detail Pesanan → Tandai Lunas.",
        },
      },
      {
        heading: "Tips",
        bullets: [
          "Cetak QR dan tempel di stand meja yang mudah dilihat.",
          "Beri label meja yang jelas (Meja 1, Meja 2) supaya pesanan mudah diantar.",
          "Aktifkan Kitchen Display kalau dapurmu butuh papan pesanan real-time.",
        ],
      },
    ],
  },
  {
    slug: "kitchen-display-antrian",
    category: "Panduan",
    title: "Cara Pakai Kitchen Display (KDS) & Layar Antrian di SellOn",
    excerpt:
      "Tampilkan pesanan masuk di layar dapur dan nomor antrian di layar pelanggan. Dapur tahu apa yang harus dimasak, pelanggan tahu kapan pesanannya siap.",
    publishedAt: "2026-05-29",
    readingTime: "4 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/kitchen-display-antrian/cover.png",
    plan: "pro",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: dapur punya papan pesanan real-time dan pelanggan punya layar antrian — alur dapur jadi rapi tanpa teriak-teriak nomor pesanan.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Paket Pro. Aktifkan KDS di Pengaturan → Meja & QR. Buka KDS dari menu Kitchen Display.",
        },
      },
      {
        heading: "1. Papan dapur (Kitchen Display)",
        paragraphs: [
          "Buka Kitchen Display lalu jadikan layar penuh di tablet/monitor dapur. Pesanan masuk muncul di kolom Antrian. Klik Mulai Masak untuk memindahkannya ke Disiapkan, lalu Tandai Siap saat selesai (pindah ke Siap Diantar). Semua update real-time tanpa perlu refresh.",
        ],
        image: {
          src: "/tutorials/kitchen-display-antrian/01-kds.png",
          alt: "Kitchen Display: tiga kolom Antrian, Disiapkan, Siap Diantar dengan kartu pesanan dan tombol Mulai Masak/Tandai Siap",
          caption: "Papan dapur — Antrian → Disiapkan → Siap.",
        },
      },
      {
        heading: "2. Layar antrian pelanggan",
        paragraphs: [
          "Buka halaman antrian publik di alamat /q/nama-toko dan tampilkan di TV/tablet area tunggu. Pelanggan melihat nomor pesanan yang Sedang Disiapkan dan yang Siap Diambil — update otomatis seiring dapur menggerakkan pesanan di KDS.",
        ],
        image: {
          src: "/tutorials/kitchen-display-antrian/02-antrian.png",
          alt: "Layar antrian publik: nomor Sedang Disiapkan dan Siap Diambil",
          caption: "Layar antrian publik untuk pelanggan.",
        },
      },
      {
        heading: "Tips",
        bullets: [
          "Pakai tablet murah atau TV dengan browser untuk KDS dan layar antrian.",
          "KDS dan layar antrian update real-time — pastikan perangkatnya online.",
          "Gabungkan dengan QR Meja supaya pesanan self-order langsung masuk ke dapur.",
        ],
      },
    ],
  },
  {
    slug: "pembayaran",
    category: "Panduan",
    title: "Cara Atur Pembayaran (Midtrans, Transfer, QRIS) di SellOn",
    excerpt:
      "Aktifkan pembayaran otomatis lewat Midtrans, atau terima transfer bank manual dan QRIS statis. Dana selalu masuk langsung ke rekeningmu — SellOn tidak pernah pegang uang pembeli.",
    publishedAt: "2026-05-29",
    readingTime: "5 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/pembayaran/cover.png",
    plan: "free",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: pembeli punya cara bayar yang jelas, dan setiap rupiah masuk langsung ke rekeningmu. Kamu bisa pakai pembayaran otomatis (Midtrans) atau cara manual (transfer bank + QRIS statis).",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Buka Pengaturan → Pembayaran. Untuk Midtrans, siapkan akun Midtrans sendiri. Untuk manual, cukup nomor rekening / foto QRIS.",
        },
      },
      {
        heading: "1. Pembayaran otomatis lewat Midtrans",
        paragraphs: [
          "Di bagian Midtrans, masukkan Server Key dan Client Key dari dashboard Midtrans-mu. Pakai mode Sandbox dulu untuk testing (pembeli tidak di-charge), lalu ganti ke Live saat siap. Klik Tes Koneksi untuk memastikan kunci benar. Setelah aktif, pembeli bisa bayar otomatis (kartu, e-wallet, VA) dan status order ter-update sendiri.",
        ],
        image: {
          src: "/tutorials/pembayaran/01-pembayaran.png",
          alt: "Pengaturan Pembayaran: Midtrans (sandbox/live, server & client key) dan Rekening Manual & QRIS Statis",
          caption: "Pengaturan pembayaran — Midtrans + manual + QRIS.",
        },
      },
      {
        heading: "2. Transfer bank manual & QRIS statis",
        paragraphs: [
          "Belum mau pakai Midtrans? Klik Tambah di bagian Rekening Manual & QRIS Statis untuk menambahkan nomor rekening bank atau foto QRIS statis-mu. Pembeli transfer/scan, lalu upload bukti bayar di halaman pesanan mereka. Kamu verifikasi dan tandai lunas. Cocok untuk yang baru mulai (paket Gratis).",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Mulai dengan transfer manual + QRIS statis kalau belum punya Midtrans — gratis dan cepat.",
          "Selalu tes koneksi Midtrans di Sandbox sebelum mengaktifkan mode Live.",
          "Verifikasi mutasi rekening sebelum menandai pesanan lunas untuk transfer manual.",
        ],
      },
    ],
  },
  {
    slug: "pengiriman-ongkir",
    category: "Panduan",
    title: "Cara Atur Pengiriman & Ongkir di SellOn",
    excerpt:
      "Set kota asal, pilih kurir, dan tentukan ambang gratis ongkir. Ongkir dihitung otomatis di checkout supaya pembeli tahu total bayar yang pasti.",
    publishedAt: "2026-05-29",
    readingTime: "4 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/pengiriman-ongkir/cover.png",
    plan: "free",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: ongkir terhitung otomatis di checkout sesuai tujuan pembeli, dan kamu bisa menawarkan gratis ongkir di atas nominal tertentu.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Buka Pengaturan → Pengiriman. Untuk ongkir real-time, pilih kota asal dari daftar RajaOngkir.",
        },
      },
      {
        heading: "1. Set kota asal",
        paragraphs: [
          "Pilih Kota / Kabupaten Asal paketmu. Kalau dipilih dari daftar RajaOngkir, ongkir di checkout dihitung real-time sesuai jarak. Kalau tidak terkonfigurasi, SellOn pakai estimasi tabel bawaan (zone-based) berdasarkan nama kota fallback.",
        ],
        image: {
          src: "/tutorials/pengiriman-ongkir/01-pengiriman.png",
          alt: "Pengaturan Pengiriman: kota asal (RajaOngkir) dan daftar kurir aktif seperti JNE",
          caption: "Atur kota asal dan kurir aktif.",
        },
      },
      {
        heading: "2. Pilih kurir aktif",
        paragraphs: [
          "Centang kurir yang mau muncul di checkout (JNE, dll). Kurir bertanda Live menarik harga real-time dari RajaOngkir saat asal dan tujuan terhubung; sisanya pakai estimasi tabel bawaan.",
        ],
      },
      {
        heading: "3. Gratis ongkir",
        paragraphs: [
          "Set ambang gratis ongkir (free shipping threshold): kalau total belanja pembeli melewati nominal yang kamu tentukan, ongkir otomatis digratiskan. Trik klasik untuk menaikkan nilai keranjang.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Isi berat & dimensi produk supaya perhitungan ongkir lebih akurat.",
          "Ambang gratis ongkir sebaiknya sedikit di atas rata-rata belanja, supaya mendorong tambah barang.",
          "Aktifkan beberapa kurir agar pembeli bisa pilih yang paling murah/cepat.",
        ],
      },
    ],
  },
  {
    slug: "whatsapp",
    category: "Panduan",
    title: "Cara Atur Template & Notifikasi WhatsApp di SellOn",
    excerpt:
      "Siapkan template pesan WhatsApp (konfirmasi, pembayaran, resi) dengan variabel otomatis, dan set nomor notifikasi supaya kamu tahu tiap ada order masuk.",
    publishedAt: "2026-05-29",
    readingTime: "4 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/whatsapp/cover.png",
    plan: "free",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: kamu bisa kirim pesan ke pembeli sekali klik dengan teks yang sudah terisi otomatis (nomor order, nama, total), dan dapat notifikasi tiap ada order baru.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Buka Pengaturan → WhatsApp.",
        },
      },
      {
        heading: "1. Set nomor notifikasi",
        paragraphs: [
          "Isi Nomor WhatsApp tujuan untuk menerima notifikasi order. Format bebas (0812…, 62812…, atau +62812…) — sistem menormalkan sendiri. Aktifkan notifikasi, lalu Simpan.",
        ],
        image: {
          src: "/tutorials/whatsapp/01-whatsapp.png",
          alt: "Pengaturan WhatsApp: nomor notifikasi dan editor template dengan variabel seperti {{order_number}}",
          caption: "Atur nomor notifikasi dan template pesan.",
        },
      },
      {
        heading: "2. Edit template pesan",
        paragraphs: [
          "Sesuaikan template untuk konfirmasi pesanan, link pembayaran, dan update resi. Pakai variabel seperti {{order_number}}, {{customer_name}}, {{total}}, dan {{order_link}} — saat dikirim, variabel otomatis terganti data pesanan asli. Template inilah yang terisi saat kamu klik kirim WA dari halaman detail pesanan.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Tulis template yang hangat dan personal — sebut nama pembeli lewat {{customer_name}}.",
          "Selalu sertakan {{order_link}} supaya pembeli mudah cek status pesanannya.",
          "Jaga pesan ringkas; satu pesan, satu tujuan (konfirmasi / bayar / resi).",
        ],
      },
    ],
  },
  {
    slug: "tim-akses",
    category: "Panduan",
    title: "Cara Undang Staf & Atur Akses Tim di SellOn",
    excerpt:
      "Ajak staf bantu kelola toko tanpa berbagi akun pribadi. Undang lewat email Google dan tentukan perannya — pemilik tetap kamu.",
    publishedAt: "2026-05-29",
    readingTime: "3 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/tim-akses/cover.png",
    plan: "free",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: staf-mu bisa bantu kelola pesanan dan produk lewat akun mereka sendiri, dengan akses yang kamu atur — tanpa kamu perlu kasih password.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Buka Pengaturan → Tim. Staf perlu punya (atau akan membuat) akun Google.",
        },
      },
      {
        heading: "1. Undang staf",
        paragraphs: [
          "Klik Undang Staf, masukkan Email Google staf (harus sama dengan akun Google mereka), pilih Role, lalu klik Undang. Kalau mereka sudah punya akun SellOn, langsung ditambahkan. Kalau belum, statusnya “Pending” dan otomatis aktif saat mereka login pertama kali dengan email itu.",
        ],
        image: {
          src: "/tutorials/tim-akses/01-tim.png",
          alt: "Halaman Tim: daftar anggota, seat terpakai, dan tombol Undang Staf",
          caption: "Halaman Tim — anggota dan kuota seat.",
        },
      },
      {
        heading: "2. Pilih peran yang tepat",
        paragraphs: [
          "Saat mengundang, tentukan peran staf — misalnya Staf untuk operasional pesanan & produk. Pemilik (kamu) tetap punya kontrol penuh; staf tidak bisa menghapus toko atau mengubah langganan.",
        ],
        image: {
          src: "/tutorials/tim-akses/02-undang-staf.png",
          alt: "Dialog Undang Staf Baru: isi email Google dan pilih Role",
          caption: "Undang staf + pilih perannya.",
        },
      },
      {
        heading: "Tips",
        bullets: [
          "Pakai email Google yang benar — undangan terikat ke email itu.",
          "Beri peran seminimal yang dibutuhkan untuk keamanan toko.",
          "Cabut akses staf yang sudah tidak aktif lewat tombol hapus.",
        ],
      },
    ],
  },
  {
    slug: "domain-kustom",
    category: "Panduan",
    title: "Cara Pasang Domain Kustom di SellOn",
    excerpt:
      "Pakai domain atau subdomain milik sendiri (mis. toko.brandkamu.com) untuk toko online-mu. HTTPS otomatis aktif setelah domain terhubung.",
    publishedAt: "2026-05-29",
    readingTime: "3 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/domain-kustom/cover.png",
    plan: "bisnis",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: toko online-mu tampil di domain sendiri (mis. toko.brandkamu.com), bukan sellon.id/nama-toko — lebih profesional dan mudah diingat.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Fitur ini tersedia di paket Bisnis, dan kamu perlu punya domain/subdomain sendiri. Buka Pengaturan → Domain.",
        },
      },
      {
        heading: "1. Masukkan domain kamu",
        paragraphs: [
          "Di Pengaturan → Domain, isi Domain atau Subdomain (mis. toko.brandkamu.com) — masukkan nama domain saja, tanpa https:// atau path. Klik Simpan.",
        ],
        image: {
          src: "/tutorials/domain-kustom/01-domain.png",
          alt: "Pengaturan Custom Domain: input domain/subdomain dan tombol Simpan",
          caption: "Masukkan domain/subdomain milikmu.",
        },
      },
      {
        heading: "2. Arahkan DNS & tunggu aktif",
        paragraphs: [
          "Ikuti instruksi pengarahan DNS dari penyedia domainmu agar menunjuk ke SellOn. Setelah domain terhubung, HTTPS (gembok hijau) aktif otomatis — pembeli langsung bisa membuka tokomu di domain itu dengan aman.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Subdomain (toko.brandkamu.com) biasanya paling mudah diarahkan lewat CNAME.",
          "Perubahan DNS bisa butuh beberapa menit sampai jam untuk menyebar.",
          "Pastikan menulis domain tanpa https:// dan tanpa garis miring di akhir.",
        ],
      },
    ],
  },
  {
    slug: "reseller-dropship",
    category: "Panduan",
    title: "Cara Pakai Program Reseller & Dropship di SellOn",
    excerpt:
      "Jadi supplier yang punya jaringan reseller, atau jadi reseller yang jual produk orang lain tanpa stok. Begini cara kerja program reseller di SellOn.",
    publishedAt: "2026-05-29",
    readingTime: "5 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/reseller-dropship/cover.png",
    plan: "pro",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: kamu bisa memperluas jualan lewat dua peran. Sebagai supplier, kamu undang reseller untuk menjualkan produkmu. Sebagai reseller/dropshipper, kamu jual produk supplier lain tanpa perlu stok sendiri.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Paket Pro. Menu ada di grup PROGRAM RESELLER pada sidebar. Fitur ini paling fleksibel — kenali dua perannya dulu.",
        },
      },
      {
        heading: "Sebagai supplier: buat program reseller",
        paragraphs: [
          "Buka Program Supplier (Program Reseller Saya). Klik Buat Program, lalu Kelola Produk untuk memilih produk mana yang ditawarkan ke reseller. Tiap program punya Kode Undangan unik — bagikan kode ini ke calon reseller supaya mereka bisa gabung. Lihat siapa saja yang sudah bergabung lewat Lihat Reseller.",
        ],
        image: {
          src: "/tutorials/reseller-dropship/01-program-reseller.png",
          alt: "Program Reseller Saya: program aktif, kode undangan, kelola produk, dan lihat reseller",
          caption: "Sisi supplier — buat program & bagikan kode undangan.",
        },
      },
      {
        heading: "Sebagai reseller: gabung & import produk",
        paragraphs: [
          "Buka Katalog Reseller, klik Gabung Program Baru, dan masukkan kode undangan dari supplier. Setelah gabung, import produk supplier ke tokomu untuk dijual ulang. Harga jualmu sendiri yang tentukan.",
        ],
        image: {
          src: "/tutorials/reseller-dropship/02-katalog-reseller.png",
          alt: "Katalog Reseller: gabung program baru dan import produk supplier",
          caption: "Sisi reseller — gabung program & import produk.",
        },
      },
      {
        heading: "Order dropship",
        paragraphs: [
          "Saat ada pembeli memesan produk hasil resell, pesanan muncul di Order Dropship dan diteruskan ke supplier untuk dikirim. Daftar supplier sumber resell-mu ada di Supplier Saya.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Sebagai supplier, pilih produk yang stoknya cukup sebelum mengundang banyak reseller.",
          "Sebagai reseller, pastikan ada selisih harga yang sehat antara harga supplier dan harga jualmu.",
          "Ganti kode undangan kalau bocor ke pihak yang tidak diinginkan.",
        ],
      },
    ],
  },
  {
    slug: "langganan-plan",
    category: "Panduan",
    title: "Cara Atur Langganan & Pilih Plan di SellOn",
    excerpt:
      "Pahami beda paket Gratis, Pro, dan Bisnis, lihat tagihan, dan upgrade saat tokomu butuh fitur lebih. Semua dari satu halaman langganan.",
    publishedAt: "2026-05-29",
    readingTime: "4 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/langganan-plan/cover.png",
    plan: "free",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: kamu tahu paketmu sekarang, kapan harus perpanjang, dan fitur apa yang terbuka kalau upgrade.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Buka Pengaturan → Berlangganan untuk lihat tier aktif dan riwayat pembayaran.",
        },
      },
      {
        heading: "1. Cek tier aktif & tagihan",
        paragraphs: [
          "Di Pengaturan → Berlangganan, terlihat Tier Aktif (Gratis/Pro/Bisnis), tanggal perpanjang, tombol Perpanjang dan Batalkan langganan, serta Riwayat Pembayaran (invoice). Status tiap invoice (Lunas/menunggu) tampil di sini.",
        ],
        image: {
          src: "/tutorials/langganan-plan/01-langganan.png",
          alt: "Halaman Berlangganan: tier aktif Pro, tanggal perpanjang, dan riwayat pembayaran",
          caption: "Halaman langganan — tier aktif & riwayat tagihan.",
        },
      },
      {
        heading: "2. Beda Gratis, Pro, dan Bisnis",
        bullets: [
          "Gratis — cocok untuk mulai: kelola produk, storefront, pesanan, pembayaran (transfer manual + QRIS), pengiriman, WhatsApp, dan pelanggan.",
          "Pro — buka fitur operasional lanjutan: Bahan Baku, Pembelian (PO), Stok Opname, Kasir POS, Dine-In/QR Meja, Kitchen Display, Loyalty, Membership, Laporan, Analytics 360, dan Program Reseller.",
          "Bisnis — semua fitur Pro plus tambahan seperti Domain Kustom (toko di domain sendiri).",
        ],
      },
      {
        heading: "3. Cara upgrade",
        paragraphs: [
          "Klik upgrade dari halaman langganan (atau dari kartu ajakan upgrade yang muncul saat kamu buka fitur berbayar). Ikuti instruksi pembayaran. Setelah aktif, fitur paket baru langsung terbuka. Untuk detail harga terbaru, lihat halaman Harga di situs SellOn.",
        ],
      },
      {
        heading: "Tips",
        bullets: [
          "Mulai dari Gratis, upgrade ke Pro saat kamu butuh kasir/stok bahan/laporan.",
          "Perpanjang sebelum jatuh tempo supaya fitur tidak terkunci di tengah jualan.",
          "Pilih Bisnis kalau kamu butuh domain sendiri atau skala yang lebih besar.",
        ],
      },
    ],
  },
  {
    slug: "bulk-upload-produk",
    category: "Panduan",
    title: "Cara Bulk Upload Produk (Impor Massal) di SellOn",
    excerpt:
      "Tambah puluhan produk sekaligus dari satu file Excel — termasuk varian, GTIN, kategori, dan resep. Yang valid langsung tersimpan, yang error muncul lengkap dengan alasannya.",
    publishedAt: "2026-05-30",
    readingTime: "5 menit",
    featured: false,
    coverColor: "from-brand-500 to-brand-700",
    coverImage: "/tutorials/bulk-upload-produk/cover.png",
    plan: "pro",
    sections: [
      {
        paragraphs: [
          "Hasil akhir: kamu bisa menambah hingga 100 produk sekaligus dari satu file Excel, tanpa input satu per satu. Cocok saat pertama kali mengisi katalog atau menambah banyak produk baru.",
        ],
        callout: {
          kind: "tip",
          title: "Yang kamu butuhkan",
          body: "Paket Pro. Buka Produk → Upload Massal. Maksimal 100 produk per file.",
        },
      },
      {
        heading: "1. Download template Excel",
        paragraphs: [
          "Di halaman Upload Massal Produk, ikuti 3 langkah yang tertera. Mulai dengan klik Download Template (.xlsx). Template berisi 2 sheet: Produk (tempat isi data) dan Petunjuk (referensi format).",
        ],
        image: {
          src: "/tutorials/bulk-upload-produk/01-cara-pakai.png",
          alt: "Halaman Upload Massal Produk: 3 langkah cara pakai dan tombol Download Template",
          caption: "Mulai dengan download template Excel.",
        },
      },
      {
        heading: "2. Isi data produk",
        paragraphs: [
          "Isi mulai baris 2 (baris 1 adalah header — jangan diubah). Hapus baris contoh, lalu masukkan datamu. Kolom wajib: Nama Produk, Harga, Stok. Harga ditulis angka tanpa titik/koma (contoh: 35000).",
        ],
        bullets: [
          "Kolom opsional: Deskripsi, Status (active/inactive/sold_out), Berat & Dimensi, Foto URL 1–5.",
          "Varian — format 'Nama:Harga:Stok[:SKU]' dipisah titik-koma, mis. 'S:85000:5;M:85000:10'.",
          "GTIN (barcode), Kategori (sesuai nama), dan Resep (NamaBahan:Qty) juga bisa diisi.",
          "Pastikan tiap baris punya URL Slug unik, atau kosongkan supaya dibuat otomatis.",
        ],
      },
      {
        heading: "3. Upload & baca hasilnya",
        paragraphs: [
          "Drop file ke kolom upload (atau klik untuk pilih), lalu klik Mulai Upload. Proses berjalan di latar belakang — kamu bebas pindah halaman, notifikasi progress tetap muncul di pojok kanan atas sampai selesai. Tiap baris divalidasi: yang valid langsung tersimpan, yang error muncul beserta alasannya (mis. harga kosong, atau slug sudah dipakai). Perbaiki di Excel lalu upload ulang — produk yang sudah tersimpan tidak akan terduplikat.",
        ],
        image: {
          src: "/tutorials/bulk-upload-produk/02-hasil-upload.png",
          alt: "Notifikasi hasil upload: 2 berhasil, 2 gagal, dengan detail error per baris (harga wajib diisi, slug sudah dipakai)",
          caption: "Hasil upload — yang valid tersimpan, error dijelaskan per baris.",
        },
      },
      {
        heading: "Tips",
        bullets: [
          "Lebih dari 100 produk? Pecah jadi beberapa file.",
          "Isi Kategori dan Resep di template sekalian, supaya tidak perlu edit satu-satu nanti.",
          "Kalau ada baris error, cukup perbaiki baris itu dan upload ulang — sisanya tidak terpengaruh.",
        ],
      },
    ],
  },
];
